import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Typography } from "@mui/material";
import { useUser } from "@/context/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const {user} = useUser();
  console.log('user sign in....', user);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Typography variant="h1">
            hello world hello world hello world hello world hello world hello
            world hello world hello world hello world
          </Typography>
        </div>
      </main>
    </>
  );
}
